// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwfqUDeEoVTi_0OE2CL_qogbfjjhG-DwQ',
    appId: '1:771445747812:web:465ce53c38cfce8622ef71',
    messagingSenderId: '771445747812',
    projectId: 'kickin-9s7gfx',
    authDomain: 'kickin-9s7gfx.firebaseapp.com',
    storageBucket: 'kickin-9s7gfx.firebasestorage.app',
    measurementId: 'G-RWLQS35RTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9WXShp7U5Kk_V9hQZRGdDtx9VEpxOBOc',
    appId: '1:771445747812:android:7f6e5dea2e0a577b22ef71',
    messagingSenderId: '771445747812',
    projectId: 'kickin-9s7gfx',
    storageBucket: 'kickin-9s7gfx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdsWswkBDFnpNzaXhQfdldxpDML-4Uo_0',
    appId: '1:771445747812:ios:748d307419e28f9022ef71',
    messagingSenderId: '771445747812',
    projectId: 'kickin-9s7gfx',
    storageBucket: 'kickin-9s7gfx.firebasestorage.app',
    androidClientId: '771445747812-4b208m8nj0u12a5vv8a1t80eo3lr0gng.apps.googleusercontent.com',
    iosClientId: '771445747812-k4i64g33kvbmelq0ugt2hp0l5ssd4eme.apps.googleusercontent.com',
    iosBundleId: 'com.example.kickin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdsWswkBDFnpNzaXhQfdldxpDML-4Uo_0',
    appId: '1:771445747812:ios:748d307419e28f9022ef71',
    messagingSenderId: '771445747812',
    projectId: 'kickin-9s7gfx',
    storageBucket: 'kickin-9s7gfx.firebasestorage.app',
    androidClientId: '771445747812-4b208m8nj0u12a5vv8a1t80eo3lr0gng.apps.googleusercontent.com',
    iosClientId: '771445747812-k4i64g33kvbmelq0ugt2hp0l5ssd4eme.apps.googleusercontent.com',
    iosBundleId: 'com.example.kickin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwfqUDeEoVTi_0OE2CL_qogbfjjhG-DwQ',
    appId: '1:771445747812:web:76e03433e6d8ec7f22ef71',
    messagingSenderId: '771445747812',
    projectId: 'kickin-9s7gfx',
    authDomain: 'kickin-9s7gfx.firebaseapp.com',
    storageBucket: 'kickin-9s7gfx.firebasestorage.app',
    measurementId: 'G-0VPYWQL2RT',
  );
}
