import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:google_fonts/google_fonts.dart';
import 'terms_of_service_model.dart';
export 'terms_of_service_model.dart';

class TermsOfServiceWidget extends StatefulWidget {
  const TermsOfServiceWidget({super.key});

  static String routeName = 'terms_of_service';
  static String routePath = 'terms_of_service';

  @override
  State<TermsOfServiceWidget> createState() => _TermsOfServiceWidgetState();
}

class _TermsOfServiceWidgetState extends State<TermsOfServiceWidget> {
  late TermsOfServiceModel _model;

  final scaffoldKey = GlobalKey<ScaffoldState>();

  @override
  void initState() {
    super.initState();
    _model = createModel(context, () => TermsOfServiceModel());

    logFirebaseEvent('screen_view',
        parameters: {'screen_name': 'terms_of_service'});
    WidgetsBinding.instance.addPostFrameCallback((_) => safeSetState(() {}));
  }

  @override
  void dispose() {
    _model.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Title(
        title: 'terms_of_service',
        color: FlutterFlowTheme.of(context).primary.withAlpha(0XFF),
        child: GestureDetector(
          onTap: () {
            FocusScope.of(context).unfocus();
            FocusManager.instance.primaryFocus?.unfocus();
          },
          child: Scaffold(
            key: scaffoldKey,
            backgroundColor: FlutterFlowTheme.of(context).primaryBackground,
            body: Padding(
              padding: EdgeInsetsDirectional.fromSTEB(0.0, 24.0, 0.0, 0.0),
              child: SingleChildScrollView(
                child: Column(
                  mainAxisSize: MainAxisSize.max,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Padding(
                      padding:
                          EdgeInsetsDirectional.fromSTEB(12.0, 24.0, 0.0, 0.0),
                      child: ClipRRect(
                        borderRadius: BorderRadius.circular(8.0),
                        child: SvgPicture.network(
                          'https://grbbdskhtdettoddpxfl.supabase.co/storage/v1/object/public/storage/assest/Kickin%20Logo.svg',
                          width: 45.0,
                          height: 45.0,
                          fit: BoxFit.cover,
                        ),
                      ),
                    ),
                    Padding(
                      padding:
                          EdgeInsetsDirectional.fromSTEB(12.0, 0.0, 12.0, 0.0),
                      child: Column(
                        mainAxisSize: MainAxisSize.max,
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Column(
                            mainAxisSize: MainAxisSize.max,
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text(
                                'Terms & Conditions',
                                style: FlutterFlowTheme.of(context)
                                    .headlineSmall
                                    .override(
                                      font: GoogleFonts.oswald(
                                        fontWeight: FlutterFlowTheme.of(context)
                                            .headlineSmall
                                            .fontWeight,
                                        fontStyle: FlutterFlowTheme.of(context)
                                            .headlineSmall
                                            .fontStyle,
                                      ),
                                      letterSpacing: 0.0,
                                      fontWeight: FlutterFlowTheme.of(context)
                                          .headlineSmall
                                          .fontWeight,
                                      fontStyle: FlutterFlowTheme.of(context)
                                          .headlineSmall
                                          .fontStyle,
                                    ),
                              ),
                              Text(
                                'This document is an electronic record in terms of the Information Technology Act, 2000 and rules made thereunder, including the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.\n\nThis Terms of Use document is published in accordance with Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011. It sets forth the rules and regulations, privacy policy, and terms of use for access or usage of the domain https://kickin.in, including related mobile sites and mobile applications (collectively referred to as the \"Platform\").\n\nThe Platform is owned and operated by Arpit Singh Rawat, sole proprietor of Kickin, a sole proprietorship registered under Udyam, with its principal place of business in Delhi, India (hereinafter referred to as “Kickin,” “we,” “us,” or “our”).\n\nYour use of the Platform and services, including but not limited to browsing, registering, posting, participating in events or tournaments, and receiving updates, constitutes your acceptance of and agreement to these Terms of Use and our Privacy Policy. If you do not agree with these terms, you must not use or access the Platform.\n\nAcceptance of Terms\n\nBy accessing or using the Kickin App (“App”), website, or related services (collectively, “Services”), you agree to be bound by these Terms of Use and our Privacy Policy. If you do not agree, please refrain from using the Services.\n\n\nPermissions & User Consent\nThe App may request certain device permissions to enable optimal functionality. \nThese include:\n\nLocation Access: To help you discover nearby events, matches, and tournaments. This can be disabled via your device settings.\n\nCamera & Gallery Access: Required for uploading photos and videos to posts or tournaments.\n\nMicrophone Access: If voice features are introduced (e.g., voice chats, commentary), access may be requested.\n\nNotifications: Push notifications may be used to deliver important tournament updates, messages, or feature announcements. You may manage preferences through device settings.\n\nUser Responsibilities\n\nYou agree to the following responsibilities as a user of Kickin:\n\nAccount Accuracy: You will provide true, current, and complete information during registration and keep it updated.\n\nContent Submission: You are solely responsible for content you upload (e.g., posts, videos, profile info), and must ensure it does not infringe on any third-party rights or applicable laws.\n\nAccount Security: You are responsible for all activity under your account and must maintain confidentiality of your login credentials.\n\nCompliance: You agree to use the Platform in compliance with all applicable Indian laws and these Terms of Use.\nProhibited Activities\n\nYou agree not to:\n\nUse the Platform for unlawful, harmful, abusive, defamatory, obscene, or fraudulent purposes.\n\nDisrupt the operation or integrity of the Platform or its systems (e.g., hacking, introducing viruses).\n\nUpload or distribute content that violates intellectual property, privacy rights, or public decency standards.\nIntellectual Property\n\nAll contents of the App/Platform, including but not limited to the design, layout, graphics, text, software, and trademarks, are the intellectual property of Kickin and/or its licensors. You are not granted any license or right to use them without express written permission.\n\nThird-Party Services & Links\n\nOur Platform may contain links to third-party websites or services. Once you leave Kickin’s environment, you will be governed by their terms and privacy policies. We are not responsible for any content or actions of such third-party platforms.\nUpdates & Modifications\n\nWe reserve the right to modify these Terms of Use at any time. Material updates will be notified through the Platform. Continued use of the Services after any updates constitutes acceptance of the modified Terms.\n\nSuspension or Termination\n\nWe may, at our sole discretion, suspend or terminate your access to the Platform if:\nYou breach these Terms or any applicable law;\n\nWe detect fraudulent, harmful, or unauthorized behavior;\n\nWe are required to comply with a legal obligation or regulation.\n\nLimitation of Liability\nT\no the fullest extent permitted by law, Kickin shall not be liable for any indirect, incidental, consequential, special, or punitive damages, including but not limited to loss of profits, business interruption, or data loss arising from your use or inability to use the Services. Our total liability, if any, shall not exceed Rs. 100 or the amount you paid (if any) for using the Services giving rise to the claim—whichever is lower.\n\nIndemnity\n\nYou agree to indemnify and hold harmless Kickin, its proprietor, affiliates, agents, and employees from and against all losses, liabilities, claims, damages, penalties, and expenses arising out of your use of the Platform, breach of these Terms, or violation of any law or third-party rights.\nForce Majeure\n\nKickin shall not be held liable for any failure or delay in performance due to events beyond our control, including but not limited to natural disasters, technical failures, legal restrictions, or acts of God.\nGoverning Law & Jurisdiction\n\nThese Terms shall be governed by and construed in accordance with the laws of India. All disputes arising from or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts located in Delhi, India.\nContact Information\n\nFor any questions, complaints, or legal notices, please contact:\nArpit Singh Rawat\nProprietor – Kickin\nEmail: arpit@kickin.in\nPhone: +91 9821990780\nWebsite: https://kickin.in\n\nBy continuing to use Kickin, you confirm that you have read, understood, and agree to be bound by these Terms of Use.',
                                style: FlutterFlowTheme.of(context)
                                    .bodyMedium
                                    .override(
                                      font: GoogleFonts.poppins(
                                        fontWeight: FlutterFlowTheme.of(context)
                                            .bodyMedium
                                            .fontWeight,
                                        fontStyle: FlutterFlowTheme.of(context)
                                            .bodyMedium
                                            .fontStyle,
                                      ),
                                      letterSpacing: 0.0,
                                      fontWeight: FlutterFlowTheme.of(context)
                                          .bodyMedium
                                          .fontWeight,
                                      fontStyle: FlutterFlowTheme.of(context)
                                          .bodyMedium
                                          .fontStyle,
                                    ),
                              ),
                            ].divide(SizedBox(height: 24.0)),
                          ),
                        ].divide(SizedBox(height: 24.0)),
                      ),
                    ),
                  ].divide(SizedBox(height: 32.0)),
                ),
              ),
            ),
          ),
        ));
  }
}
